### ISSUE TITLE
how tabnet with perform in the p >> n situation?

### ISSUE THREAD

**Issue by parsifal9** [mlverse/tabnet#100]
Hi Tabnet,

Do you have any insight on how tabnet with perform in the p >> n situation?

I have done the tutorial at https://blogs.rstudio.com/ai/posts/2021-02-11-tabnet/
with a data set of 11M by 29. However the use cases I am intersted in are in genomics where the
data sets are closer to the transpose of that.
    
I have tried a small test data set is 150 x 14000 and in this case the runtime grows a lot.
Do I have any hope?
What about future developments?

Bye

**Comment by cregouby** [comment]
Hello @parsifal9, 

I'm not from the single-cell genomic business, but I think tabnet cannot do that. 
This is because, by design, there is far too much degree of freedom in the tabnet network parameter to train on 29 samples.

**Comment by cregouby** [comment]
and to my knowledge, the Seurat methodology can not be challenged so easily ;-)

**Comment by cregouby** [comment]
but in case you have a very large number of  observations n without outcome, you can try to pre-train the tabnet model with them. That maybe could help the convergence with a tiny supervised data budget...
