### ISSUE TITLE
Using tabnet_config() inside fit_resamples

### ISSUE THREAD

**Issue by ruddnr** [mlverse/tabnet#102]
Is there a way to use tabnet_config() inside fit_resamples() ?
I would like to use early stopping option but tabnet() does not have that argument.

**Comment by ruddnr** [comment]
Oh, I just have to use ```set_args()``` when creating model specification.

**Comment by cregouby** [comment]
Hello @ruddnr,
It seems that you found a solution to the issue. So I close it.
Feel free to reoppen it if needed.
