### ISSUE TITLE
Save and load model with Tidymodel and .rds

### ISSUE THREAD

**Issue by clementrx** [mlverse/tabnet#128]
Hi, 
I'm trying to save and load model in another R session :
```
mod_bundle <- bundle(fitted_model)
saveRDS(mod_bundle, here::here("model", "model_tabnet.rds"))

# in new session 
model_open = readRDS(here::here("model", "model_tabnet.rds"))
mod_unbundled <- unbundle(model_open)

```
And I when I try to predict I have the following message : 
```
Error in `check_model_exists()`:
! Model `tabnet` has not been registered.
```

What can I do ? 

Thanks

**Comment by cregouby** [comment]
Hello Clement, 

Model saving shall be straightforward into Rds file without the need to `unbundle()` anything.
An example is in there : https://github.com/mlverse/tabnet/blob/d6411d246ff8695e721208cc296fb659fedf64ab/tests/testthat/test-hardhat_scenarios.R#L83-L98

Hope it helps.
