### ISSUE TITLE
Add support for Apple silicon GPUs

### ISSUE THREAD

**Issue by gacolitti** [mlverse/tabnet#132]
I know `{torch}` added some support for Apple silicon GPUs (device = 'mps') in [torch v0.9.0](https://blogs.rstudio.com/ai/posts/2022-10-25-torch-0-9/#support-for-apple-silicon). 

Can `{tabnet}` also leverage Apple silicon GPUs?

**Comment by cregouby** [comment]
Hello @gacolitti,

{tabnet} completely relies on {torch} capability to use `device = 'mps'`. So there should be zero issue there. 

Feel free to publish a successful experiment on the MPS device and or close the issue.
