### ISSUE TITLE
display training progress

### ISSUE THREAD

**Issue by skeydan** [mlverse/tabnet#16]
can you please display progress while training? thanks!

**Comment by skeydan** [comment]
just noticed that it's there when you use the tidymodels API (before I was executing `tabnet_fit`) :-)

**Comment by skeydan** [comment]
as I'm at it - the whole issue is not that important :-) - may I suggest that if doing cross-validation, we display the fold we're working on?

**Comment by dfalbel** [comment]
This can be done with tidymodels, see eg: https://tune.tidymodels.org/reference/control_grid.html
For displaying a progressbar when training you can pass `verbose=TRUE` when calling `set_engine`.

**Comment by skeydan** [comment]
thanks! (this issue originally referred to the code in the README, where there's no `set_engine` ... but in reality, I'd use the code from your answer anyway (((or even the workflow approach))))

**Comment by dfalbel** [comment]
if you are using `tabnet_fit` you could pass the `verbose` argument directly to the function.
