### ISSUE TITLE
unsupervised pre-training

### ISSUE THREAD

**Issue by dfalbel** [mlverse/tabnet#18]

**Comment by cregouby** [comment]
Design questions
 - [x] pretraining function name : `tabnet_pretrain()`
 - [ ] pretraining recipe format for data shall support the **identical** recipe as for supervised part for consistency with `tabnet_fit()` ?
 - [ ] pretraining formula format for data shall support the **identical** formula as for supervised part ?
 - [ ] pretraining data.frame format for data shall expect x, y, ... consistent with `tabnet_fit()` ( thus with y being trashed, wich will be misleading ) ?

**Comment by dfalbel** [comment]
I think at first I would only support a data.frame method taking only `x` as input.

I would still use `hardhat::mold()` for input preprocessing mostly for factor level handling, in this case we might need to pass a dummy y vector, that could be just `rep(1, nrow(x))`.
