### ISSUE TITLE
Support for CUDA 11.0?

### ISSUE THREAD

**Issue by chriscardillo** [mlverse/tabnet#32]
Hi and thanks for this awesome project.

Trying to try it out on Ubuntu 20.04 using CUDA 11.0 and CuDNN 8. I have made sure to install the current dev version of `torch`, as suggested by [this torch comment](https://github.com/mlverse/torch/issues/348#issuecomment-754347733), and have confirmed that my installation of torch is successfully using my GPU by running `torch::cuda_is_available()`.

I am attempting to run the below:

```r
library(tabnet)
library(tidymodels)

set.seed(1)

data("lending_club", package="modeldata")

split <- initial_split(lending_club, strata = Class)
train <- training(split)
test  <- testing(split)

rec <- recipe(Class ~ ., train) %>%
  step_normalize(all_numeric())


mod <- tabnet(epochs = 1, batch_size = 128) %>%
  set_engine("torch", verbose = TRUE) %>%
  set_mode("classification")


wf <- workflow() %>%
  add_model(mod) %>%
  add_recipe(rec)


mod_fit <- wf %>%
  fit(train)
```

I end up with the following error:

```
Error in (function (weight, indices, padding_idx, scale_grad_by_freq,  : 
  Input, output and indices must be on the current device
Exception raised from index_select_out_cuda at /pytorch/aten/src/ATen/native/cuda/Indexing.cu:819 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f00ee682b89 in /home/chris/R/x86_64-pc-linux-gnu-library/4.0/torch/deps/./libc10.so)
frame #1: at::native::index_select_out_cuda(at::Tensor&, at::Tensor const&, long, at::Tensor const&) + 0x94f (0x7f0087621a5f in /home/chris/R/x86_64-pc-linux-gnu-library/4.0/torch/deps/./libtorch_cuda.so)
frame #2: at::native::index_select_cuda(at::Tensor const&, long, at::Tensor const&) + 0x6e (0x7f0087621dfe in /home/chris/R/x86_64-pc-linux-gnu-library/4.0/torch/deps/./libtorch_cuda.so)
frame #3: <unknown function> + 0x4010d65 (0x7f0088822d65 in /home/chris/R/x86_64-pc-linux-gnu-library/4.0/torch/deps/./libtorch_cuda.so)
frame #4: <unknown function> + 0x1361767 (0x7f00dea2076
Timing stopped at: 15.19 0.749 15.21
```

Curious if this is a CUDA issue. Have you seen this error before? If so, is there a known remedy?

Thanks for your help here.

**Comment by dfalbel** [comment]
Hi @chriscardillo 

Thanks very much for reporting!

I think this issue is related to this one: https://github.com/mlverse/tabnet/issues/20
Which we fixed in the current dev version of tabnet.

Could you try also installing tabnet from github?

**Comment by chriscardillo** [comment]
Confirming that installing the dev version of tabnet solved my problem. Thank you!

**Comment by dfalbel** [comment]
Thanks @chriscardillo ! We will submit a new version to CRAN soon.
