### ISSUE TITLE
Saving/Loading tabnet models

### ISSUE THREAD

**Issue by mdancho84** [mlverse/tabnet#34]
Hey, I'm wondering what the most effective way to save/load a tabnet model is. I know `torch::torch_save()` and `torch::torch_load()` exist. Not sure if there is a convenient way to save/load.

**Comment by mdancho84** [comment]
Typically there's a serialization function that allows us to read the underlying model. That's what I normally have to do with TensorFlow and MXNet.

**Comment by dfalbel** [comment]
In theory, saveRDS should just work. The model object contains a version of the serialized weights, so we reload it as needed. We test this here:

https://github.com/mlverse/tabnet/blob/46ac191be0ded5db1381e6c3c49b055d561cbfcc/tests/testthat/test-hardhat.R#L203-L224

There could be a bug depending if you are using CRAN or dev versions of torch.

**Comment by mdancho84** [comment]
Ok, so the problem was that I was not using the development versions of the `torch` and `tabnet` packages. I can save workflows that contain fitted `tabnet` models with `readr::write_rds()`.

## Solution:

```
# GITHUB INSTALLATIONS ----
# TORCH: 
remotes::install_github("mlverse/torch")
# TABNET: 
remotes::install_github("mlverse/tabnet")
```

**Comment by mdancho84** [comment]
It actually looks like it's still not working for me. Not sure what the deal is. The workaround I'm using is this serialization process:

```
# Serialization
write_rds(wflw_tabnet_fit, "models/wflw_tabnet_fit.rds")

torch::torch_save(wflw_tabnet_fit$fit$fit$fit$fit$network, "models/torch_network")

# Loading
torch_network <- torch::torch_load("models/torch_network")

wflw_fit <- read_rds("models/wflw_tabnet_fit.rds")

wflw_fit$fit$fit$fit$fit$network <- torch_network

wflw_fit
```

**Comment by dfalbel** [comment]
OK! I'll investigate

**Comment by mdancho84** [comment]
Ok, for what it's worth, I'm getting pretty good results with `tabnet`. I'm doing some tests now, and I'll be showcasing this project during my Learning Lab 51 - Torch for Tabular Data. The saving/loading is a small inconvenience.

**Comment by dfalbel** [comment]
I could not reproduce this issue any longer with dev versions...  The test should be more robust with: aa1f85f
Let me know if this persists.

**Comment by mdancho84** [comment]
Ok thank you!
