### ISSUE TITLE
tabnet_config and tabnet_fit

### ISSUE THREAD

**Issue by cmcmaster1** [mlverse/tabnet#38]
It would seem natural that `tabnet_config` could be called outside of the `tabnet_fit` function, so hyperparameters are declared upfront. At the moment `tabet_config` creates a list, but the `do.call` function on "..." in the `tabnet_fit` function will make this a list of a list. We would still like to preserve the ability to change the hyperparameters within the `tabnet_fit` function.

This could be achieved by making `config` a named argument and updating it from "..." using `modifyList`. For example:

```
tabnet_pretrain.data.frame <- function(x, y, tabnet_model = NULL, config = tabnet_config(), ..., from_epoch = NULL) {
  processed <- hardhat::mold(x, y)
  config <- modifyList(config, list(...))
  tabnet_bridge(processed, config = config, tabnet_model, from_epoch, task="unsupervised")
}
```

**Comment by dfalbel** [comment]
I agree! That makes perfect sense for me. Do you want to file a PR?

**Comment by cmcmaster1** [comment]
Will do (might take me a moment - first ever PR, will get my wife to help me!)
