### ISSUE TITLE
Fixing sparsemax and adding entmax

### ISSUE THREAD

**Issue by cmcmaster1** [mlverse/tabnet#47]
Just jotting down some insights here. The problem with the sparsemax implementation is that `d <- input$size(-1)` does not behave like it would in pytorch.

The `size` method defined in torch:
```
size = function(dim) {
      x <- cpp_tensor_dim(self$ptr)
      
      if (missing(dim))
        return(x)
      
      x[dim]
    }
```

If dim is set to -1, this gives a vector of sizes for all dimensions except the first dimension. This is different behaviour to pytorch, where this would give a single number, the size of the final dimension.

The following work-around can be put in sparsemax:

```
sparsemax <- torch::nn_module(
  "sparsemax",
  initialize = function(dim = -1) {
    self$dim <- dim
  },
  forward = function(input) {
    # Work-around:
    if (self$dim == -1) {
      self$dim <- input$dim()
    }
    sparsemax_function(input, self$dim)
  }
)
```

This works completely fine when I test it on my machine, but it does not work in testing when I have submitted a PR. I also have entmax working on my machine.

**Comment by cregouby** [comment]
Hello @cmcmaster1, we would love to help on your P.R. on that.

**Comment by cmcmaster1** [comment]
@cregouby great! I have made a PR #48
