### ISSUE TITLE
Failed to install 'tabnet' from GitHub on Windows (also, R session aborts on Mac)

### ISSUE THREAD

**Issue by jcutler79** [mlverse/tabnet#50]
I'm trying to install torch and tabnet. I've tried remotes::install_github("mlverse/tabnet") and was able to install both torch and tabnet on my mac. However, after executing code to fit a tabnet model, it causes the session to abort (whether I try it in RStudio or base R it causes it to abort/quit). So now I've tried to see if I could get it to work on my Windows computer at work. However, on Windows, it fails to install (using remotes::install_github). The error says

Error: Failed to install 'tabnet' from GitHub: (converted from warning) cannot remove prior installation of package 'utf8'

This is kind of a multifaceted issue since I also ran into a similar error with installing torch on Windows (the package that couldn't be removed was 'ps' rather than 'utf8'), and since I'm talking about one kind of problem on a Mac and another on Windows. Sorry about that. I'm not sure if you guys want to address torch installation issues as well.

**Comment by jcutler79** [comment]
Update: On my Mac I just did the installation for torch using install.packages("torch") instead of the github install. The installation worked fine, but unfortunately after I tried running the code again it caused the session to abort same as before. Is there an install.packages option for tabnet?

**Comment by jcutler79** [comment]
Maybe it's because I'm running R 3.6.1. I'll try updating to 3.6.2

**Comment by jcutler79** [comment]
Good news! I got it to work on my mac after updating to R 4.0.5. I am getting the "R session aborted" problem on my windows computer now, but at least it's working on my mac!

**Comment by cregouby** [comment]
Hello @jcutler79,
Sorry for letting you try to workaround it on your own.  
As you can see in https://github.com/mlverse/tabnet/pull/44/checks?check_run_id=2268928743, the setup is tested working with R 4.0.5 on windows and macOS.
For your windows setup, it could be  that one former installation occurred with different user or different access right on your machine. I would recommend you a brand new and recent install of R.
Hope it helps,

**Comment by cregouby** [comment]
Hello @jcutler79, 
Is it still a bug related to tabnet package ? If not you can maybe close the issue.
