### ISSUE TITLE
Tensor Size Error

### ISSUE THREAD

**Issue by nnimaa** [mlverse/tabnet#53]
Hello everyone, 

Could someone please help me understand what the issue is here? Here is a very simple example: https://www.dropbox.com/s/i9muap0v0aqa45x/data.Rda?dl=0

`library(tabnet)`
`load('data.Rda')`
`fit=tabnet_fit(xx, yy)`

Error in cpp_Function_apply(torch_variable_list(.env$variables)$ptr, .f_,  : 
  Evaluation error: The size of tensor a (98) must match the size of tensor b (97) at non-singleton dimension 1
Exception raised from infer_size at ../aten/src/ATen/ExpandUtils.cpp:24 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f6bf2b87b29 in /home/naghaeep/R/x86_64-pc-linux-gnu-library/3.6/torch/deps/./libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd2 (0x7f6bf2b84ab2 in /home/naghaeep/R/x86_64-pc-linux-gnu-library/3.6/torch/deps/./libc10.so)
frame #2: at::infer_size(c10::ArrayRef<long>, c10::ArrayRef<long>) + 0x4d9 (0x7f6be1089069 in /home/naghaeep/R/x86_64-pc-linux-gnu-library/3.6/torch/deps/./libtorch_cpu.so)
frame #3: at::TensorIteratorBase::compute_shape(at::TensorIteratorConfig const&) + 0xde (0x7f6be10c383e in /home/na

And session info:
`> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tabnet_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6      ps_1.6.0        fansi_0.4.2     withr_2.4.2    
 [5] utf8_1.2.1      crayon_1.4.1    R6_2.5.0        lifecycle_1.0.0
 [9] hardhat_0.1.5   magrittr_2.0.1  coro_1.0.1      pillar_1.6.0   
[13] rlang_0.4.10    callr_3.7.0     vctrs_0.3.7     ellipsis_0.3.1 
[17] bit64_4.0.5     torch_0.3.0     glue_1.4.2      bit_4.0.4      
[21] processx_3.5.1  compiler_3.6.3  pkgconfig_2.0.3 tibble_3.1.1   

`

**Comment by cregouby** [comment]
Hello @nnimaa 

I've tried to reproduce your issue, and it's not occuring on my setup.
```r
> load("/tmp/mozilla_cg0/data.Rda")
> library(tabnet)
> tabnet_fit(xx,yy)
An `nn_module` containing 12,043 parameters.

── Modules ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
• embedder: <embedding_generator> #0 parameters
• tabnet: <tabnet_no_embedding> #12,042 parameters

── Parameters ───────────────────────────────────────────────────────────────────────────────────────────────────────────
• .check: Float [1:1]
```
I would recommend you to upgrade to the latest version of tabnet through `remotes::install_github("mlverse/tabnet")` as a lot of changes and fix have been done since version 0.1.0 you are using.

**Comment by Unco3892** [comment]
Using the CRAN release I've ran into the same issue as @nnimaa , however upgrading to the latest release on GitHub solves the issue.

**Comment by nnimaa** [comment]
Thank you everyone. This worked for me as well. Closing the issue :)
