### ISSUE TITLE
Rstudio on EC2 instance crashes when torch is called

### ISSUE THREAD

**Issue by G3Jram** [mlverse/tabnet#56]
Hi,

I am working on EC2 instance. When i call the tabnet_fit function, it crashes the R session saying all the workspace data is lost. 

I am only using a few numeric columns and a target column from a reasonably small dataset.

Any help will be much appreciated. Thanks.

**Comment by dfalbel** [comment]
I think this can be related to a problem in the torch installation. Can you check that you can do `torch::torch_tensor(1)` in that machine?

**Comment by G3Jram** [comment]
Hi,

Its giving the same error msg when i do that. "The previous R session was abnormally terminated due to an unexpected crash.

**Comment by cregouby** [comment]
Hello @G3Jram ,
 so here you encounter a `torch::` installation issue, not a `tabnet::` issue. Torch is the underlying deeplearning framework of Tabnet. I think it is worth for you to reoppen the issue in here: https://github.com/mlverse/torch/issues, if the problem remains after you check all the installation prerequisite in https://torch.mlverse.org/docs/articles/installation.html.
Hope it will helps you enjoy using Tabnet.

**Comment by G3Jram** [comment]
Hi,

Im have succeeded in implementing tabnet in python instead. Waiting for the torch error to get sorted on the R side.. 

However, after building the model if i want to look at the feature importances, im not too sure how to do it.

Tabnet doesnt need shap to understand the features right?..

I actually want ti plot the features by importance.

Please help.

**Comment by cregouby** [comment]
Hello @G3Jram ,
the R implementation includes the `tabnet_explain()` function with associated plot that will give you feature importance for each prediction as documented in https://mlverse.github.io/tabnet/articles/interpretation.html. This provides you the internal model feature importance, so you don't have to suffer the drawbacks of surrogate models like shap.

**Comment by skeydan** [comment]
we have a post on that in fact: https://blogs.rstudio.com/ai/posts/2021-02-11-tabnet/

**Comment by G3Jram** [comment]
Hi,

Sorry if i wasnt clear. I am after the feature importance in python not R for now as i still face torch installation issues in R.

Any help in python would be good.

Thanks.

**Comment by dfalbel** [comment]
You can find examples for the python API here: https://github.com/dreamquark-ai/tabnet/blob/develop/forest_example.ipynb

Also, I think for questions on the Python interface It's better if you ask in their repository: https://github.com/dreamquark-ai/tabnet
