### ISSUE TITLE
Scaling in the example prediction wrong

### ISSUE THREAD

**Issue by tenshis** [mlverse/tabnet#58]
When replicating the README example, the results of the prediction are still scaled/centered and attempting to use tidy to un-normalize them throws this error:

`No tidy method for objects of class tabnet_fit`

Is there a simple way to un-scale the predictions?

**Comment by cregouby** [comment]
The issue is still valid, so I keep it open for further investigation  (and documentation)

**Comment by cregouby** [comment]
The README example is a binary classification and prevent normalization on the `all_outcomes()` variables. So I think there is a misunderstanding here. May I recommend you to add a ReprEx to this issue so that we are on the same page ?
