### ISSUE TITLE
finalize_workflow() on fitted workflow incl. tabnet

### ISSUE THREAD

**Issue by simonschoe** [mlverse/tabnet#59]
Hi there,
I am wondering if this is my fault or if the `finalize_workflow()` warpper is simply not adapted for tabnet models. In short, I try to run the following code which results in an error:
```r
final_fit_tabnet <- 
  workflow(rec_tabnet, spec_tabnet) %>% 
    finalize_workflow(select_best(fit_tabnet, metric = "mae")) %>% 
    last_fit(time_split, metrics = performance_metrics)
```
```
Error in update.default(object = list(args = list(epochs = ~3, penalty = ~1e-06, : need an object with call component
```
`fit_tabnet` is the result of `tune_race_anova()`, containing all the tuning results.

Best,
Simon

**Comment by dfalbel** [comment]
This looks like a bug! It seems tat we need to implement an `update` method in order to be able to use `finalize_workflow` correctly.

Here's an example implementation for the mars model.
