### ISSUE TITLE
Features of type logical yield unclear importance scores

### ISSUE THREAD

**Issue by jemus42** [mlverse/tabnet#72]
When an input feature is `logical`, the resulting importance scores stored in `.$fit$importances` contain two distinct scores for the `TRUE` and `FALSE` level, which seems like a bug or at least unexpected behavior.
Given that this is not the case for other categorical or binary numeric features, I assume it might be the former.

Is it possible that common normalisation/preprocessing steps in the tidymodels framework prevents this from occurring in regular applications?

``` r
library(tabnet)

set.seed(2)
# Training data with logical feature --------------------------------------
xdat <- tibble::tibble(
  feat_factor = factor(sample(letters, 100, replace = TRUE)),
  feat_numeric = rnorm(100),
  feat_integer = sample(100, replace = TRUE),
  feat_logical = sample(c(TRUE, FALSE), 100, replace = TRUE),
  target = factor(sample(c("yes", "no"), 100, replace = TRUE))
)

model_fit <- tabnet_fit(target ~ ., data = xdat, epochs = 3)

# Distinct importance scores for TRUE and FALSE seem... odd
model_fit$fit$importances
#> # A tibble: 5 × 2
#>   variables         importance
#>   <chr>                  <dbl>
#> 1 feat_numeric           0.132
#> 2 feat_integer           0.154
#> 3 feat_logicalFALSE      0.309
#> 4 feat_logicalTRUE       0.141
#> 5 feat_factor            0.264

# Recoded to integer ------------------------------------------------------
xdat$feat_logical <- as.integer(xdat$feat_logical)

model_fit2 <- tabnet_fit(target ~ ., data = xdat)

# Importance scores as expected, one per input feature
model_fit2$fit$importances
#> # A tibble: 4 × 2
#>   variables    importance
#>   <chr>             <dbl>
#> 1 feat_numeric     0.0451
#> 2 feat_integer     0.736 
#> 3 feat_logical     0.0947
#> 4 feat_factor      0.125
```

<sup>Created on 2021-12-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cregouby** [comment]
After some investigation, the bug comes from a differentiated behavior of hardhat::mold() that we use to process data.

Interestingly, problem only occurs on formula, neither on data.frame nor reciepe.

## Workaround : switch from `formula` to `recipe` or to `data.frame` :
``` r
library(tabnet)

set.seed(2)
# Training data with logical feature --------------------------------------
xdat <- tibble::tibble(
  feat_factor = factor(sample(letters, 100, replace = TRUE)),
  feat_numeric = rnorm(100),
  feat_integer = sample(100, replace = TRUE),
  feat_logical = sample(c(TRUE, FALSE), 100, replace = TRUE),
  target = factor(sample(c("yes", "no"), 100, replace = TRUE))
)

model_fit <- tabnet_fit(recipes::recipe(target ~ ., data=xdat), data = xdat, epochs = 3)

# Distinct importance scores for TRUE and FALSE seem... odd
model_fit$fit$importances
#> # A tibble: 4 × 2
#>   variables    importance
#>   <chr>             <dbl>
#> 1 feat_factor      0.358 
#> 2 feat_numeric     0.205 
#> 3 feat_integer     0.399 
#> 4 feat_logical     0.0384
```

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cregouby** [comment]
The author of {hardhat} gave back to me with
"The whole point of the formula interface is to use `model.matrix()` with _very_ little modifications, so on first thought I don't think we are going to want to make any changes here." 
And this is an explicit behavior of  `model.matrix()` to turn factors and logical into dummy variables, as per https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/library/stats/R/models.R#L642
This mean we will have to leave with it !

Thanks for reporting anyway !
