### ISSUE TITLE
Release Tabnet 0.4.0

### ISSUE THREAD

**Issue by cregouby** [mlverse/tabnet#81]
Prepare for release:

* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_tabnet.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `devtools::build_readme()`
* [x] [`urlchecker::url_check()`](https://github.com/r-lib/urlchecker)
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] Update `cran-comments.md`
* [ ] Review pkgdown reference index for, e.g., missing topics
* [ ] Draft blog post

Submit to CRAN:

* [ ] `usethis::use_version('minor')`
* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version()`
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by dfalbel** [comment]
@cregouby Feel free to take maintainership role if you want.

You would only need to change those lines:

https://github.com/mlverse/tabnet/blob/f4f815f43e017ab3b6169e730b74037397041033/DESCRIPTION#L5-L6

so you get the `'cre'` role.

**Comment by cregouby** [comment]
I'll do ! 
Thanks !

**Comment by cregouby** [comment]
@dfalbel, I think I'm not mature enough on that task. Would you be kind enough to take over ?
