### ISSUE TITLE
hyperparameter tuning questions

### ISSUE THREAD

**Issue by 3SMMZRjWgS** [mlverse/tabnet#88]
Sorry if my 2 questions below sound noobish:

1. In the original TabNet [paper](https://arxiv.org/pdf/1908.07442.pdf) under "Guidelines for hyperparameters" section, it talks about 

> "An optimal choice of γ can have a major role on the performance."

   Can someone tell me which one of the hyperparameters in tabnet_config deals with this γ?

2. Is there a package that can help auto tune the hyperparameters for a Tabnet?

**Comment by cregouby** [comment]
Hello @3SMMZRjWgS 

1) The `gamma` parameter in the paper and original code has been renamed `feature_reusage` in `tabnet_config()` function. It defaults to 1.3

2) You can tune this hyper-parameter through any method you want using the {workflow} package for example. For his you need to use the `tabnet()` command  to fit tabnet models using {parsnip} machinery. You can derive the [workflow test](https://github.com/mlverse/tabnet/blob/e08f76dbdb0e9bc1bc395ee081b874ee1fa80367/tests/testthat/test-parsnip.R#L42) if that helps.

**Comment by 3SMMZRjWgS** [comment]
@cregouby: Thank you for the explanation and showing the way!
