### ISSUE TITLE
Make feature importance calc optional when fitting tabnet

### ISSUE THREAD

**Issue by egillax** [mlverse/tabnet#89]
Currently when you call tabnet::tabnet() it fits the model and then calculates feature imporances. This step can take a non trivial amount of time. When you are doing multiple fits like for hyperparameter tuning you only need the feature importances for your final model so it would be good if this step could me made optional.

**Comment by cregouby** [comment]
Very good idea @egillax ! Would you like to propose a pull request ?

**Comment by cregouby** [comment]
Thanks for the P.R. hopefully it will contribute to reduce the gap in #37 as well
