### ISSUE TITLE
Support for early stopping

### ISSUE THREAD

**Issue by dfalbel** [mlverse/tabnet#9]

**Comment by cregouby** [comment]
is it worth doing it here ? or can we rely confidently rely on `luz::` to do so ?

**Comment by dfalbel** [comment]
Yeah, I think we can wrap tabnet core into luz in the next iterations and rely on it for the that. I'll leave this open so we don't forget to test this behavior in the future.

**Comment by NJuntunen** [comment]
Hi! first of all thanks for a great package that you guys have made. I am currently running tests on tabnet and early stopping feature is one that I am currently really missing of. Is this luz implementation already done, or is it still coming in a next iteration and if so do you have any thoughts about the schedule? Thanks in advance.

**Comment by cregouby** [comment]
Hello @NJuntunen and thanks for feedback on using Tabnet.
Luz integration did not start yet, and Luz will be the way to get early stopping, I guess. 
In the meantime, you should be able to do it on your own : 
-  fork the project and make a branch for early-stopping,
-  add  early-stopping code in the training loop in `model.R` ( I would put it before the scheduler step in https://github.com/mlverse/tabnet/blob/6a2a1f64bc1cf0ba3ceb9daaf6fa51b45dfb1d35/R/model.R#L450 )
- add early stopping parameters in `tabnet_config()` function and reuse them in the training loop as config$parameter

Hope it helps,  C.R.
